# =============================================
# ANDROVIX-J API - Configuración de base de datos
# =============================================

# Nombre de la aplicación
spring.application.name=androvix-j

# Conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/androvixj
spring.datasource.username=postgres
spring.datasource.password=bestpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

